[package]
name = "gws_native"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
edition = "2018"

[dependencies]
simon = "0.2"
whoami = "0.4"
gws_prototty = { path = "../prototty" }
