[package]
name = "gws_unix"
version = "0.1.0"
authors = ["Stephen Sherratt <sfsherratt@gmail.com>"]
edition = "2018"

[dependencies]
prototty_unix = { version = "0.25", features = ["storage"] }
gws_prototty = { path = "../prototty" }
gws_native = { path = "../native" }
